name: Module Manifest Validation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate_manifest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Check main entry point exists
      run: |
        python -c "
        import json
        try:
          with open('module-manifest.json') as f:
            manifest = json.load(f)
        except FileNotFoundError:
          print('Error: module-manifest.json not found')
          exit(1)
        
        required_keys = ['name', 'version', 'description', 'main', 'author', 'contributors']

        missing_keys = [key for key in required_keys if key not in manifest]

        if missing_keys:
            print(f'Error: The following keys are missing in manifest: {", ".join(missing_keys)}')
            exit(1)
        else:
            print('All required keys found in manifest')
            exit(0)
        "
