name: Module Manifest Validation

on:
  pull_request:
    branches:
      - main

jobs:
  validate_manifest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Check main entry point exists
      run: |
        import os
        import json

        manifest_path = os.path.join(os.getenv('GITHUB_WORKSPACE'), 'module-manifest.json')
        print(manifest_path)
        if not os.path.exists(manifest_path):
          print('Error: module-manifest.json not found')
          exit(1)

        with open(manifest_path) as f:
          manifest = json.load(f)

        required_keys = ['name', 'version', 'description', 'main', 'author', 'contributors']

        missing_keys = [key for key in required_keys if key not in manifest]

        if missing_keys:
          print('Error: The following keys are missing in manifest: ' + ', '.join(missing_keys))
          exit(1)
        else:
          print('All required keys found in manifest')
          exit(0)
